//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.11 at 07:58:05 PM EST 
//


package com.nayakam.mail.checkworks;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ChecklistType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ChecklistType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="response-email">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="email-to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sections">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="section" type="{http://itree.com.au/checkworks}SectionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChecklistType", propOrder = {

})
public class ChecklistType {

    @XmlElement(name = "response-email", required = true)
    protected ChecklistType.ResponseEmail responseEmail;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected ChecklistType.Sections sections;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the responseEmail property.
     *
     * @return possible object is
     * {@link ChecklistType.ResponseEmail }
     */
    public ChecklistType.ResponseEmail getResponseEmail() {
        return responseEmail;
    }

    /**
     * Sets the value of the responseEmail property.
     *
     * @param value allowed object is
     * {@link ChecklistType.ResponseEmail }
     */
    public void setResponseEmail(ChecklistType.ResponseEmail value) {
        this.responseEmail = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the sections property.
     *
     * @return possible object is
     * {@link ChecklistType.Sections }
     */
    public ChecklistType.Sections getSections() {
        return sections;
    }

    /**
     * Sets the value of the sections property.
     *
     * @param value allowed object is
     * {@link ChecklistType.Sections }
     */
    public void setSections(ChecklistType.Sections value) {
        this.sections = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="email-to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "emailTo",
            "subject"
    })
    public static class ResponseEmail {

        @XmlElement(name = "email-to", required = true)
        protected String emailTo;
        @XmlElement(required = true)
        protected String subject;

        /**
         * Gets the value of the emailTo property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getEmailTo() {
            return emailTo;
        }

        /**
         * Sets the value of the emailTo property.
         *
         * @param value allowed object is
         * {@link String }
         */
        public void setEmailTo(String value) {
            this.emailTo = value;
        }

        /**
         * Gets the value of the subject property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getSubject() {
            return subject;
        }

        /**
         * Sets the value of the subject property.
         *
         * @param value allowed object is
         * {@link String }
         */
        public void setSubject(String value) {
            this.subject = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="section" type="{http://itree.com.au/checkworks}SectionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "section"
    })
    public static class Sections {

        @XmlElement(required = true)
        protected List<SectionType> section;

        /**
         * Gets the value of the section property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the section property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSection().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SectionType }
         */
        public List<SectionType> getSection() {
            if (section == null) {
                section = new ArrayList<SectionType>();
            }
            return this.section;
        }

    }

}
