//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.11 at 07:58:05 PM EST 
//


package com.nayakam.mail.checkworks;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the checkworks package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Checklist_QNAME = new QName("http://itree.com.au/checkworks", "checklist");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: checkworks
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link ChoiceResponseType }
     * 
     */
    public ChoiceResponseType createChoiceResponseType() {
        return new ChoiceResponseType();
    }

    /**
     * Create an instance of {@link QuestionType }
     * 
     */
    public QuestionType createQuestionType() {
        return new QuestionType();
    }

    /**
     * Create an instance of {@link ChecklistType }
     * 
     */
    public ChecklistType createChecklistType() {
        return new ChecklistType();
    }

    /**
     * Create an instance of {@link NumberResponseType }
     * 
     */
    public NumberResponseType createNumberResponseType() {
        return new NumberResponseType();
    }

    /**
     * Create an instance of {@link TextResponseType }
     * 
     */
    public TextResponseType createTextResponseType() {
        return new TextResponseType();
    }

    /**
     * Create an instance of {@link DatetimeResponseType }
     * 
     */
    public DatetimeResponseType createDatetimeResponseType() {
        return new DatetimeResponseType();
    }

    /**
     * Create an instance of {@link LocationResponseType }
     * 
     */
    public LocationResponseType createLocationResponseType() {
        return new LocationResponseType();
    }

    /**
     * Create an instance of {@link SectionType.Questions }
     * 
     */
    public SectionType.Questions createSectionTypeQuestions() {
        return new SectionType.Questions();
    }

    /**
     * Create an instance of {@link ChoiceResponseType.Choices }
     * 
     */
    public ChoiceResponseType.Choices createChoiceResponseTypeChoices() {
        return new ChoiceResponseType.Choices();
    }

    /**
     * Create an instance of {@link QuestionType.Responses }
     * 
     */
    public QuestionType.Responses createQuestionTypeResponses() {
        return new QuestionType.Responses();
    }

    /**
     * Create an instance of {@link ChecklistType.ResponseEmail }
     * 
     */
    public ChecklistType.ResponseEmail createChecklistTypeResponseEmail() {
        return new ChecklistType.ResponseEmail();
    }

    /**
     * Create an instance of {@link ChecklistType.Sections }
     * 
     */
    public ChecklistType.Sections createChecklistTypeSections() {
        return new ChecklistType.Sections();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChecklistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://itree.com.au/checkworks", name = "checklist")
    public JAXBElement<ChecklistType> createChecklist(ChecklistType value) {
        return new JAXBElement<ChecklistType>(_Checklist_QNAME, ChecklistType.class, null, value);
    }

}
