//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.11 at 07:58:05 PM EST 
//


package com.nayakam.mail.checkworks;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for QuestionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuestionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responses">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="text-response" type="{http://itree.com.au/checkworks}TextResponseType"/>
 *                   &lt;element name="datetime-response" type="{http://itree.com.au/checkworks}DatetimeResponseType"/>
 *                   &lt;element name="location-response" type="{http://itree.com.au/checkworks}LocationResponseType"/>
 *                   &lt;element name="choice-response" type="{http://itree.com.au/checkworks}ChoiceResponseType"/>
 *                   &lt;element name="number-response" type="{http://itree.com.au/checkworks}NumberResponseType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuestionType", propOrder = {
    "text",
    "responses"
})
public class QuestionType {

    @XmlElement(required = true)
    protected String text;
    @XmlElement(required = true)
    protected QuestionType.Responses responses;
    @XmlAttribute(name = "sequence")
    protected Integer sequence;

    /**
     * Gets the value of the text property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the responses property.
     *
     * @return
     *     possible object is
     *     {@link QuestionType.Responses }
     *
     */
    public QuestionType.Responses getResponses() {
        return responses;
    }

    /**
     * Sets the value of the responses property.
     *
     * @param value
     *     allowed object is
     *     {@link QuestionType.Responses }
     *
     */
    public void setResponses(QuestionType.Responses value) {
        this.responses = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSequence(Integer value) {
        this.sequence = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="text-response" type="{http://itree.com.au/checkworks}TextResponseType"/>
     *         &lt;element name="datetime-response" type="{http://itree.com.au/checkworks}DatetimeResponseType"/>
     *         &lt;element name="location-response" type="{http://itree.com.au/checkworks}LocationResponseType"/>
     *         &lt;element name="choice-response" type="{http://itree.com.au/checkworks}ChoiceResponseType"/>
     *         &lt;element name="number-response" type="{http://itree.com.au/checkworks}NumberResponseType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "textResponseOrDatetimeResponseOrLocationResponse"
    })
    public static class Responses {

        @XmlElements({
            @XmlElement(name = "text-response", type = TextResponseType.class),
            @XmlElement(name = "datetime-response", type = DatetimeResponseType.class),
            @XmlElement(name = "location-response", type = LocationResponseType.class),
            @XmlElement(name = "choice-response", type = ChoiceResponseType.class),
            @XmlElement(name = "number-response", type = NumberResponseType.class)
        })
        protected List<Object> textResponseOrDatetimeResponseOrLocationResponse;

        /**
         * Gets the value of the textResponseOrDatetimeResponseOrLocationResponse property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textResponseOrDatetimeResponseOrLocationResponse property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextResponseOrDatetimeResponseOrLocationResponse().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextResponseType }
         * {@link DatetimeResponseType }
         * {@link LocationResponseType }
         * {@link ChoiceResponseType }
         * {@link NumberResponseType }
         * 
         * 
         */
        public List<Object> getTextResponseOrDatetimeResponseOrLocationResponse() {
            if (textResponseOrDatetimeResponseOrLocationResponse == null) {
                textResponseOrDatetimeResponseOrLocationResponse = new ArrayList<Object>();
            }
            return this.textResponseOrDatetimeResponseOrLocationResponse;
        }

    }

}
